// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuavedhziuctbjybofgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1YXZlZGh6aXVjdGJqeWJvZmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMzk5MDYsImV4cCI6MjA4NzYxNTkwNn0.kqAaOmorYVph6ubmh9lMFS0djPBtrkYJIXrNeZ3o76Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});